name: video_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  lottie: ^3.1.2
  fluttertoast: ^8.2.6
  firebase_core: ^3.1.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.0.1
  pod_player: ^0.2.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
    - asset/lottie/

